/**
 * Regenerates `docs/tools.md` from the tool definitions themselves.
 *
 * Reads the built output rather than the sources, because Node's type stripping cannot resolve
 * the `.js` specifiers TypeScript uses internally. Run `npm run docs:tools`, which builds first.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { allTools, connectTools, DEFAULT_TOOLSETS, TOOLSETS } from '../dist/index.js';
import type { ToolDefinition, Toolset } from '../dist/index.js';

// Setup tools are built per server around a live credential session. Only their metadata is read
// here, so the placeholders never reach a handler.
const setupTools = connectTools(undefined as never, () => ({ form: false, url: false }));

const TOOLSET_SUMMARY: Record<Toolset, string> = {
  core: 'Administrations, contacts, products, ledger accounts, tax rates, identities and users.',
  invoicing:
    'Sales invoices, recurring invoices, estimates, external sales invoices and subscriptions.',
  purchases: 'Purchase invoices, receipts, documents and general journal documents.',
  banking: 'Financial accounts, financial mutations, payments and purchase transactions.',
  time: 'Time entries and projects.',
  reports:
    'Profit and loss, balance sheet, the other `/reports` endpoints, financial statements and downloads.',
  assets: 'Fixed assets and their depreciation.',
  tasks: 'Task lists, tasks, task list templates and workflows.',
  webhooks: 'Webhook subscriptions, the customer contact portal and verifications.',
};

/** Markdown tables break on pipes and newlines, and a description may legitimately contain both. */
function cell(text: string): string {
  return text
    .replace(/\s*\n\s*/g, ' ')
    .replace(/\|/g, '\\|')
    .trim();
}

function accessLabel(tool: ToolDefinition): string {
  return tool.irreversible ? `${tool.access} (irreversible)` : tool.access;
}

function section(toolset: Toolset, tools: readonly ToolDefinition[]): string {
  const lines = [`## ${toolset}`, '', TOOLSET_SUMMARY[toolset], ''];

  const enabledByDefault = DEFAULT_TOOLSETS.includes(toolset);
  lines.push(
    enabledByDefault
      ? '_Enabled by default._'
      : `_Off by default. Enable with \`--toolsets ${[...DEFAULT_TOOLSETS, toolset].join(',')}\` or \`--toolsets all\`._`,
    '',
  );

  if (tools.length === 0) {
    lines.push('_No tools._', '');
    return lines.join('\n');
  }

  lines.push('| Tool | Access | Description |', '| --- | --- | --- |');
  for (const tool of tools) {
    lines.push(`| \`${tool.name}\` | ${accessLabel(tool)} | ${cell(tool.description)} |`);
  }
  lines.push('');
  return lines.join('\n');
}

function render(): string {
  const byToolset = new Map<Toolset, ToolDefinition[]>(TOOLSETS.map((name) => [name, []]));
  for (const tool of allTools) byToolset.get(tool.toolset)?.push(tool);

  const counts = {
    total: allTools.length,
    read: allTools.filter((tool) => tool.access === 'read').length,
    write: allTools.filter((tool) => tool.access === 'write').length,
    destroy: allTools.filter((tool) => tool.access === 'destroy').length,
  };

  const header = [
    '# Tools',
    '',
    '<!-- Generated by `npm run docs:tools`. Do not edit by hand. -->',
    '',
    `${counts.total} tools across ${TOOLSETS.length} toolsets: ${counts.read} read, ${counts.write} write, ${counts.destroy} destroy.`,
    `Plus ${setupTools.length} setup tools that are always available.`,
    '',
    'The **Access** column is the permission tier a tool needs:',
    '',
    '- `read` — always available.',
    '- `write` — creates or modifies data. Needs `--allow-write` (or `MONEYBIRD_ALLOW_WRITE=true`).',
    '- `destroy` — deletes data, or does something the API offers no way to undo. Needs both',
    '  `--allow-write` and `--allow-delete`.',
    '',
    'Tools outside those tiers are not registered at all, so a model cannot see or call them.',
    'Run `moneybird-mcp tools` to list what your current settings expose.',
    '',
    `Toolsets enabled by default: ${DEFAULT_TOOLSETS.join(', ')}.`,
    '',
    '',
  ].join('\n');

  const setup = [
    '## Setup',
    '',
    'Always registered, whatever the toolset and permission settings, because they are how a server',
    'with no working credentials gets some.',
    '',
    '| Tool | Access | Description |',
    '| --- | --- | --- |',
    ...setupTools.map(
      (tool) => `| \`${tool.name}\` | ${accessLabel(tool)} | ${cell(tool.description)} |`,
    ),
    '',
  ].join('\n');

  const sections = TOOLSETS.map((toolset) => section(toolset, byToolset.get(toolset) ?? []));
  return `${header}${setup}\n${sections.join('\n')}`;
}

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '..', 'docs', 'tools.md');
await writeFile(target, render(), 'utf8');
process.stdout.write(`Wrote ${allTools.length} tools to ${target}\n`);
